---
title: "changelog"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{changelog}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

> 2026-01-14: package creation and test with `getBathym`

-   amended DESCRIPTION to include authors
-   defined package dependencies for getBathym function
    (`use_package("__")`) - auto amends DESCRIPTION
-   created function with `use_r("getBathym")` - inserted roxygen
    skeleton to build help file (insert cursor in script, then code -\>
    insert roxygen skeleton - Created `.rd` documentation with
    `devtools::document()`
-   `usethis::use_mit_license()` - Added MIT licence
-   Added some dummy vignettes
    -   `use_vignette("changelog.Rmd")`
-   Added 'Getting started' page
-   Updated `_pkgdown.yml`
-   Added home index landing page `README.md`
-   Added Barb function `getCMEMS_l4chl.R`. Slightly rewrote code to be
    more tidy and fix duplicate column in output.

> 2026-01-16: adding new vignettes

-   Added five new vignettes, have `eval=F` in all R chunks to prevent
    evaluation (code does not work as I don't have all data required)
-   `prepare-data.rmd` only vignette that does not have eval=F in most
    chunks; draws upon RDS file that I manually saved in `ext/inst` .
-   Ensured to document() and build_site() before pushing changes to
    Github
